export enum StatusCode {
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    METHOD_NOT_ALLOWED = 405,
}
export const AccessCookie = "x-access";
export const RefreshCookie = "x-refresh";
export const CsrfName = "x-csrf";
export const instituteHeader = "x-institute-name";
export const applicationHeader = "x-application-id";
export const CSRF =
    "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
export const CSRF_SIZE = 32;

export const Groups = {
    "The Somaiya School, Mumbai": [0, 1],
    "S. K. Somaiya Prathmik Shala, Mumbai": [0],
    "S. K. Somaiya Vinay Mandir High School, Mumbai": [0, 1],
    "Somaiya Vidyamandir, Sakarwadi": [0, 1],
    "Shri Sharda English Medium School,  Kopargaon": [0, 1],
    "Somaiya Vidyamandir,  Laxmiwadi": [0],
    "Somaiya Shishu Niketan Primary School, Sameerwadi": [0],
    "Somaiya Vinaymandir High School, Sameerwadi": [0, 1],
    "K. J. Somaiya English Medium School, Sameerwadi": [0, 1],
    "Nareshwadi Learning Centre, Dahanu": [0],
    "Somaiya Vinay Mandir, Rehti": [0],
    "S. K. Somaiya Vinay Mandir Junior Institute, Mumbai": [1],
    "Somaiya Vidyamandir, Laxmiwadi": [1],
    "Smt. Sakarbai K. Somaiya Junior Institute of Education (D. Ed)": [1],
    "K J Somaiya Madhyamik Vidyalaya, Nareshwadi Learning Centre, Dahanu": [1],
    "K. J. Somaiya Private Industrial Training Institute": [1],
    "K. J. Somaiya Junior Institute of Science and Commerce": [1],
    "K. J. Somaiya Junior Institute of Arts and Commerce": [1],
    "K. J. Somaiya Institute Information Technology": [2],
    "K. J. Somaiya School of Engineering": [2],
    "K. J. Somaiya Institute of Management": [2],
    "K. J. Somaiya Polytechnic": [2],
    "K. J. Somaiya Institute Arts and Commerce": [2],
    "K. J. Somaiya Institute of Science and Commerce": [2],
    "S. K. Somaiya Institute of Arts, Science and Commerce": [2],
    "K. J. Somaiya School of Education": [2],
    "K J Somaiya Institute of Dharma Studies": [2],
    "Maya Somaiya School of Music & Performing Arts": [2],
    "Somaiya Institute of Research and Consultancy": [2],
    "Somaiya Sports Academy": [2],
    "Faculty & Staff Development Centre, SVU": [2],
    "School of Civilization Studies": [2],
    "Department of Library and Information Science": [2],
    "Admission and Student Outreach": [2],
    "Dr. Shantilal K Somaiya School of Art": [2],
    "S K Somaiya School of Commerce & Business Studies": [2],
    "Somaiya School of Humanities & Social Sciences": [2],
    "Somaiya School of Basic & Applied Science": [2],
    "Somaiya Dhwani Chitram": [2],
    "K. J. Somaiya Medical Institute and Research Centre & K. J. Somaiya Hospital":
        [3],
    "K. J. Somaiya Institute of Physiotherapy": [3],
    "K. J. Somaiya School and  Institute  of Nursing": [3],
} as const;

export type Group = (typeof Groups)[keyof typeof Groups];

export const Institutes = [
    "The Somaiya School, Mumbai",
    "S. K. Somaiya Prathmik Shala, Mumbai",
    "S. K. Somaiya Vinay Mandir High School, Mumbai",
    "Somaiya Vidyamandir, Sakarwadi",
    "Shri Sharda English Medium School,  Kopargaon",
    "Somaiya Vidyamandir,  Laxmiwadi",
    "Somaiya Shishu Niketan Primary School, Sameerwadi",
    "Somaiya Vinaymandir High School, Sameerwadi",
    "K. J. Somaiya English Medium School, Sameerwadi",
    "Nareshwadi Learning Centre, Dahanu",
    "Somaiya Vinay Mandir, Rehti",
    "The Somaiya School, Mumbai",
    "S. K. Somaiya Vinay Mandir High School, Mumbai",
    "S. K. Somaiya Vinay Mandir Junior Institute, Mumbai",
    "Somaiya Vidyamandir, Sakarwadi",
    "Shri Sharda English Medium School,  Kopargaon",
    "Somaiya Vidyamandir, Laxmiwadi",
    "Smt. Sakarbai K. Somaiya Junior Institute of Education (D. Ed)",
    "Somaiya Vinaymandir High School, Sameerwadi",
    "K J Somaiya Madhyamik Vidyalaya, Nareshwadi Learning Centre, Dahanu",
    "K. J. Somaiya Private Industrial Training Institute",
    "K. J. Somaiya English Medium School, Sameerwadi",
    "K. J. Somaiya Junior Institute of Science and Commerce",
    "K. J. Somaiya Junior Institute of Arts and Commerce",
    "K. J. Somaiya Institute Information Technology",
    "K. J. Somaiya School of Engineering",
    "K. J. Somaiya Institute of Management",
    "K. J. Somaiya Polytechnic",
    "K. J. Somaiya Institute Arts and Commerce",
    "K. J. Somaiya Institute of Science and Commerce",
    "S. K. Somaiya Institute of Arts, Science and Commerce",
    "K. J. Somaiya School of Education",
    "K J Somaiya Institute of Dharma Studies",
    "Maya Somaiya School of Music & Performing Arts",
    "Somaiya Institute of Research and Consultancy",
    "Somaiya Sports Academy",
    "Faculty & Staff Development Centre, SVU",
    "School of Civilization Studies",
    "Department of Library and Information Science",
    "Admission and Student Outreach",
    "Dr. Shantilal K Somaiya School of Art",
    "S K Somaiya School of Commerce & Business Studies",
    "Somaiya School of Humanities & Social Sciences",
    "Somaiya School of Basic & Applied Science",
    "Somaiya Dhwani Chitram",
    "K. J. Somaiya Medical Institute and Research Centre & K. J. Somaiya Hospital",
    "K. J. Somaiya Institute of Physiotherapy",
    "K. J. Somaiya School and  Institute  of Nursing",
] as const;

export const Houses = [
    "Hemis Snow Leopords",
    "Periyar Elephants",
    "Kaziranga Rhinos",
    "Kanha Tigers",
    "Gir Lions",
] as const;
