import * as z from "zod";
import { email, institute, validNumber, validString } from "..";

export const NonTeachingForm = z.object({
    id: validNumber,
    email_id: email,
    staff_name: validString,
    award_category: validString,
    institution_name: institute,
    department: validString,
    designation: validString,
    appointment_date: validString,
    somaiya_email_id: validString,
    phone_number: validString,
    q_01: validNumber,
    q_02: validNumber,
    q_03: validNumber,
    q_04: validNumber,
    q_05: validNumber,
    q_06: validNumber,
    q_07: validNumber,
    q_08: validNumber,
    q_09: validNumber,
    q_10: validNumber,
    q_11: validNumber,
    q_12: validNumber,
    q_13: validNumber,
    q_14: validNumber,
    q_15: validNumber,
    q_16: validNumber,
    q_17: validNumber,
    q_18: validNumber,
    q_19: validNumber,
    q_20: validNumber,
    q_21: validNumber,
    q_22: validNumber,
    q_23: validNumber,
    q_24: validNumber,
    proof_docs: validString,
    nominee_photograph: validString,
    ieacApproved: validString,
    ieac_scoreA: validNumber.nullable(),
    ieac_scoreB: validNumber.nullable(),
    ieacApprovedFile: validString.nullable(),
    hr_approved: validString,
});
