import * as z from "zod";
import { email, institute, validBoolean, validNumber, validString } from "..";

export const OutstandingInstitutionForm = z.object({
    id: validNumber,
    email_id: email,
    nomination_category: validString,
    institution_name: institute,
    established_In: validString,
    head_of_institution: validString,
    hoi_designation: validString,
    hoi_joining_date: z.date(),
    somaiya_mail_id: validString,
    contact_number: validString,
    q_01: validString,
    q_02: validString,
    q_03: validString,
    q_04: validString,
    q_05: validString,
    q_06: validString,
    q_07: validString,
    q_08: validString,
    q_09: validString,
    q_10: validString,
    q_11: validString,
    q_12: validString,
    q_13: validString,
    q_14: validString,
    q_15: validString,
    q_16: validString,
    q_17: validString,
    institution_ratings: validString,
    q_18: validString,
    q_19: validString,
    q_20: validString,
    q_21: validString,
    q_22: validString,
    q_23: validString,
    q_24: validString,
    q_25: validString,
    q_26: validString,
    q_27: validString,
    q_28: validString,
    q_29: validString,
    q_30: validString,
    q_31: validString,
    q_32: validString,
    q_33: validString,
    q_34: validString,
    q_35: validString,
    q_36: validString,
    q_37: validString,
    q_38: validString,
    supportings: validString,
    ieac_approved: validBoolean,
    hr_approved: validBoolean,
});

export type OutstandingInstitutionType = z.infer<
    typeof OutstandingInstitutionForm
>;
