import * as z from "zod";
import {
    arrayChoice,
    email,
    phoneNumber,
    somaiyaMail,
    serverTextArea,
    validBoolean,
    validDate,
    validNumber,
    validString,
    validYear,
} from "../../zod";
import { OutstandingInstList, Institutes } from "../../constants";

export const OutstandingInstitutionForm = z.object({
    email_id: email,
    nomination_category: arrayChoice(OutstandingInstList),
    institution_name: arrayChoice(Institutes),
    established_In: validYear,
    head_of_institution: validString,
    hoi_designation: validString,
    hoi_joining_date: validDate,
    somaiya_mail_id: somaiyaMail,
    contact_number: phoneNumber,
    q_01: serverTextArea({ maxLength: 500 }),
    q_02: serverTextArea({ maxLength: 500 }),
    q_03: serverTextArea({ maxLength: 500 }),
    q_04: serverTextArea({ maxLength: 500 }),
    q_05: serverTextArea({ maxLength: 500 }),
    q_06: serverTextArea({ maxLength: 500 }),
    q_07: serverTextArea({ maxLength: 250 }),
    q_08: serverTextArea({ maxLength: 500 }),
    q_09: serverTextArea({ maxLength: 500 }),
    q_10: serverTextArea({ maxLength: 500 }),
    q_11: serverTextArea({ maxLength: 500 }),
    q_12: serverTextArea({ maxLength: 250 }),
    q_13: serverTextArea({ maxLength: 750 }),
    q_14: serverTextArea({ maxLength: 750 }),
    q_15: serverTextArea({ maxLength: 500 }),
    q_16: serverTextArea({ maxLength: 500 }),
    q_17: serverTextArea({ maxLength: 500 }),
    institution_ratings: validNumber,
    q_18: serverTextArea({ maxLength: 1000 }),
    q_19: serverTextArea({ maxLength: 300 }),
    q_20: serverTextArea({ maxLength: 500 }),
    q_21: serverTextArea({ maxLength: 750 }),
    q_22: serverTextArea({ maxLength: 500 }),
    q_23: serverTextArea({ maxLength: 1000 }),
    q_24: serverTextArea({ maxLength: 500 }),
    q_25: serverTextArea({ maxLength: 500 }),
    q_26: serverTextArea({ maxLength: 500 }),
    q_27: serverTextArea({ maxLength: 500 }),
    q_28: serverTextArea({ maxLength: 500 }),
    q_29: serverTextArea({ maxLength: 500 }),
    q_30: serverTextArea({ maxLength: 500 }),
    q_31: serverTextArea({ maxLength: 500 }),
    q_32: serverTextArea({ maxLength: 500 }),
    q_33: serverTextArea({ maxLength: 300 }),
    q_34: serverTextArea({ maxLength: 300 }),
    q_35: serverTextArea({ maxLength: 300 }),
    q_36: serverTextArea({ maxLength: 300 }),
    q_37: serverTextArea({ maxLength: 300 }),
    q_38: serverTextArea({ maxLength: 500 }),

    supportings: validString,
    ieac_approved: validBoolean.optional().nullable(),
    hr_approved: validBoolean.optional().nullable(),
});

export type OutstandingInstitutionType = z.infer<
    typeof OutstandingInstitutionForm
>;
