import * as z from "zod";
import { email, validNumber, validString } from "..";

export const TeachingForm = z.object({
    id: validNumber,
    email_id: email,
    faculty_name: validString,
    awards_category: validString,
    institution_name: validString,
    department: validString,
    designation: validString,
    date_of_appointment: validString,
    somaiya_mail_id: email,
    contact_number: validString,
    q_01: validNumber,
    q_02: validNumber,
    q_03: validNumber,
    q_04: validNumber,
    q_05: validNumber,
    q_06: validNumber,
    q_07: validNumber,
    q_08: validNumber,
    q_09: validNumber,
    q_10: validNumber,
    q_11: validNumber,
    q_12: validNumber,
    q_13: validNumber,
    q_14: validNumber,
    q_15: validNumber,
    q_16: validNumber,
    q_17: validNumber,
    q_18: validNumber,
    q_19: validNumber,
    q_20: validNumber,
    q_21: validNumber,
    data_evidence: validString,
    profile_photograph: validString,
    ieacApproved: z.boolean(),
    ieacApprovedFile: validString.nullable(),
    ieac_scoreA: validNumber.nullable(),
    ieac_scoreB: validNumber.nullable(),
    ieac_scoreC: validNumber.nullable(),
    hr_approved: z.boolean(),
});
